# =========================================
# Namespace
# =========================================
apiVersion: v1
kind: Namespace
metadata:
  name: integrador
---
# =========================================
# RABBITMQ (AMQP) + UI
# - Usa credenciales desde Secret: rabbitmq-auth (user/pass)
# - Service tipo LoadBalancer interno para VMs GPU
# =========================================
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: integrador
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector: { app: rabbitmq }
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ui
  namespace: integrador
spec:
  type: ClusterIP
  selector: { app: rabbitmq }
  ports:
    - name: http
      port: 15672
      targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: integrador
spec:
  replicas: 1
  selector: { matchLabels: { app: rabbitmq } }
  template:
    metadata: { labels: { app: rabbitmq } }
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom: { secretKeyRef: { name: rabbitmq-auth, key: user } }
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom: { secretKeyRef: { name: rabbitmq-auth, key: pass } }
          ports:
            - containerPort: 5672
            - containerPort: 15672

# =========================================
# REDIS
# =========================================
---
apiVersion: v1
kind: Service
metadata:
  name: redis-integrador
  namespace: integrador
spec:
  type: ClusterIP
  selector: { app: redis-integrador }
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-integrador
  namespace: integrador
spec:
  replicas: 1
  selector: { matchLabels: { app: redis-integrador } }
  template:
    metadata: { labels: { app: redis-integrador } }
    spec:
      containers:
        - name: redis
          image: redis:7
          ports: [{ containerPort: 6379 }]

# =========================================
# COORDINATOR (publica a inbox del pool)
# =========================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: integrador
  labels: { app: coordinator }
spec:
  replicas: 1
  selector:
    matchLabels: { app: coordinator }
  template:
    metadata:
      labels: { app: coordinator }
    spec:
      serviceAccountName: default
      containers:
        - name: coordinador
          image: docker.io/facundootero/coordinador:latest   # o tu tag fijo
          imagePullPolicy: Always
          ports: [{ containerPort: 5000 }]
          env:
            - { name: RABBITMQ_HOST, value: "rabbitmq" }
            - { name: REDIS_HOST,    value: "redis-integrador" }
          livenessProbe:
            tcpSocket: { port: 5000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket: { port: 5000 }
            initialDelaySeconds: 5
            periodSeconds: 10

# =========================================
# WORKER-POOL
# - Declara inbox y colas de trabajo (pow.gpu TTL→DLX→pow.cpu)
# - Expone HTTP interno para /alive y /solved_task
# =========================================
---
apiVersion: v1
kind: Service
metadata:
  name: worker-pool
  namespace: integrador
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector: { app: worker-pool }
  ports:
    - name: http
      port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: integrador
  labels:
    app: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      serviceAccountName: default
      containers:
        - name: coordinador
          image: docker.io/facundootero/coordinador:latest   # o tu tag fijo
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - { name: RABBITMQ_HOST, value: "rabbitmq" }
            - { name: REDIS_HOST,    value: "redis-integrador" }
          # Probes: dejá TCP si no querés depender de /alive
          livenessProbe:
            tcpSocket: { port: 5000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket: { port: 5000 }
            initialDelaySeconds: 5
            periodSeconds: 10

# =========================================
# WORKERS CPU (escala con KEDA por backlog en pow.cpu)
# =========================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-cpu
  namespace: integrador
spec:
  replicas: 0  # KEDA escala desde 0
  selector: { matchLabels: { app: worker-cpu } }
  template:
    metadata: { labels: { app: worker-cpu } }
    spec:
      # Programar en node pool con taint (si lo configuraste)
      # nodeSelector: { pool: cpu-workers }
      # tolerations:
      #   - key: "workload"
      #     operator: "Equal"
      #     value: "cpu"
      #     effect: "NoSchedule"
      containers:
        - name: worker
          image: docker.io/facundootero/worker-cpu:latest
          imagePullPolicy: Always
          env:
            - { name: RABBITMQ_HOST,  value: "rabbitmq" }
            - { name: EXCHANGE_BLOCK, value: "ExchangeBlock" }
            # Reporta al pool (que reenvía al coordinator)
            - { name: COORDINATOR_URL, value: "http://worker-pool.integrador.svc.cluster.local:5001/solved_task" }

# =========================================
# KEDA: TriggerAuthentication + ScaledObject
# (requiere que KEDA esté instalado en el clúster)
# =========================================
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-auth
  namespace: integrador
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-conn
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-cpu-scale
  namespace: integrador
spec:
  scaleTargetRef: { name: worker-cpu }
  minReplicaCount: 0
  maxReplicaCount: 200
  pollingInterval: 5
  cooldownPeriod: 60
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: pow.cpu
        queueLength: "50"  # umbral de backlog por pod
      authenticationRef:
        name: rabbitmq-auth
