# =========================================
# Namespace
# =========================================
apiVersion: v1
kind: Namespace
metadata:
  name: integrador
---

# =========================================
# KEDA: TriggerAuthentication + ScaledObject
# (requiere que KEDA esté instalado en el clúster)
# =========================================
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-auth
  namespace: integrador
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-conn
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-cpu-scale
  namespace: integrador
spec:
  scaleTargetRef: { name: worker-cpu }
  minReplicaCount: 0
  maxReplicaCount: 200
  pollingInterval: 5
  cooldownPeriod: 60
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: pow.cpu
        queueLength: "50"  # umbral de backlog por pod
      authenticationRef:
        name: rabbitmq-auth
