apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: integrador
spec:
  replicas: 1
  selector:
    matchLabels: { app: coordinator }
  template:
    metadata:
      labels: { app: coordinator }
    spec:
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
        - name: dockerhub-cred
      containers:
        - name: coordinador
          image: docker.io/facundootero/coordinator:latest
          imagePullPolicy: Always
          env:
            - { name: RABBITMQ_HOST, value: "rabbitmq" }
            - { name: REDIS_HOST,   value: "redis-integrador" }
          ports:
            - { containerPort: 5000 }
          livenessProbe:
            tcpSocket: { port: 5000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket: { port: 5000 }
            initialDelaySeconds: 5
            periodSeconds: 10
