name: Build & Push (Docker Hub)

on:
  push:
    branches: [ main ]
    paths:
      - "apps/**"
      - ".github/workflows/build-images.yml"
    tags:
      - "v*"           # también corre para tags vX.Y.Z
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: coordinator
            context: apps/coordinator
            dockerfile: apps/coordinator/Dockerfile
          - name: worker-cpu
            context: apps/worker-cpu
            dockerfile: apps/worker-cpu/Dockerfile

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push (${{ matrix.name }})
        run: |
          set -euo pipefail
          IMAGE="docker.io/${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}"
          docker build \
            -f "${{ matrix.dockerfile }}" \
            -t "$IMAGE:${{ github.sha }}" \
            -t "$IMAGE:latest" \
            "${{ matrix.context }}"
          docker push "$IMAGE:${{ github.sha }}"
          docker push "$IMAGE:latest"

      - name: Tag & Push SemVer (${{ matrix.name }})  #    sólo  si el push vino por tag v*
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        run: |
          set -euo pipefail
          IMAGE="docker.io/${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}"
          SEMVER="${GITHUB_REF_NAME#v}"
          docker pull "$IMAGE:${GITHUB_SHA}"
          docker tag  "$IMAGE:${GITHUB_SHA}" "$IMAGE:${SEMVER}"
          docker push "$IMAGE:${SEMVER}"
