name: Build & Push (Docker Hub)
on:
  push:
    paths:
      - "apps/**"
      - ".github/workflows/build-images.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { service: [coordinator, worker-pool, worker-cpu] }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build & Push
        run: |
            # mapear coordinator -> coordinador (resto igual)
            if [ "${{ matrix.service }}" = "coordinator" ]; then REPO="coordinador"; else REPO="${{ matrix.service }}"; fi
            IMAGE="docker.io/${{ secrets.DOCKER_USERNAME }}/$REPO"
            docker build -t "$IMAGE:7d2f294963a2d1004cbb49f6c170a9dcb51fd70b" -t "$IMAGE:latest" "apps/${{ matrix.service }}"
            docker push "$IMAGE:7d2f294963a2d1004cbb49f6c170a9dcb51fd70b"
            docker push "$IMAGE:latest"
