name: Build & Push (Docker Hub)

on:
  push:
    branches: [ main ]
    paths:
      - "apps/**"
      - "Infra/k8s/manifests/coordinador.yaml"
      - ".github/workflows/build-images.yml"
    tags:
      - "v*"        # si pusheás un tag tipo v1.2.3, publica también :1.2.3
  workflow_dispatch: {}

permissions:
  contents: write     # para commitear el bump del manifest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set vars (hardcode repo + sha + semver si aplica)
        run: |
          echo "IMAGE_REPO=docker.io/facundootero/coordinator" >> $GITHUB_ENV
          echo "TAG_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          # Si el push viene por un tag vX.Y.Z, extrae  X.Y.Z
          if [[ "${GITHUB_REF_TYPE}" == "tag" && "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "TAG_SEMVER=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          else
            echo "TAG_SEMVER=" >> $GITHUB_ENV
          fi

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: facundootero
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push (sha + latest)
        uses: docker/build-push-action@v6
        with:
          context: apps/coordinator
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.TAG_SHA }}
            ${{ env.IMAGE_REPO }}:latest

      - name: Tag & Push semver (solo si hay tag vX.Y.Z)
        if: ${{ env.TAG_SEMVER != '' }}
        run: |
          docker pull "${IMAGE_REPO}:${TAG_SHA}"
          docker tag  "${IMAGE_REPO}:${TAG_SHA}" "${IMAGE_REPO}:${TAG_SEMVER}"
          docker push "${IMAGE_REPO}:${TAG_SEMVER}"

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      # Actualiza SOLO el Deployment al tag inmutable (SHA)
      - name: Bump image in manifest (Deployment only)
        env:
          MANIFEST: Infra/k8s/manifests/coordinador.yaml
          CONTAINER_NAME: coordinador          # nombre del contenedor dentro del Deployment
        run: |
          yq -i '
            (. | select(.kind=="Deployment" and .metadata.name=="coordinator")
               | .spec.template.spec.containers[]
               | select(.name==env(CONTAINER_NAME)).image
            ) = (env(IMAGE_REPO) + ":" + env(TAG_SHA))
          ' "$MANIFEST"
          echo "Preview post-change:"
          yq '. | select(.kind=="Deployment" and .metadata.name=="coordinator")
              | .spec.template.spec.containers[] | {name, image}' "$MANIFEST"

      - name: Commit & Push manifest change
        env:
          MANIFEST: Infra/k8s/manifests/coordinador.yaml
        run: |
          git config user.name  "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git add "$MANIFEST"
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: bump coordinator -> $IMAGE_REPO:$TAG_SHA"
          git push
