name: Build & Push (Docker Hub)

on:
  push:
    paths:
      - "apps/**"
      - ".github/workflows/build-images.yml"
    tags:
      - "v*"        # <--- se ejecuta también cuando empujás tags vX.Y.Z
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { service: [coordinator] }  # tu script sólo buildéa coordinator
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push (SHA + latest)
        run: |
          set -euo pipefail
          IMAGE="docker.io/${{ secrets.DOCKER_USERNAME }}/coordinator"
          docker build -t "$IMAGE:${{ github.sha }}" -t "$IMAGE:latest" apps/coordinator
          docker push "$IMAGE:${{ github.sha }}"
          docker push "$IMAGE:latest"

      # Si el push fue por un tag vX.Y.Z, publiquemos también :X.Y.Z
      - name: Tag & Push SemVer (si aplica)
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        run: |
          set -euo pipefail
          IMAGE="docker.io/${{ secrets.DOCKER_USERNAME }}/coordinator"
          SEMVER="${GITHUB_REF_NAME#v}"     # quita el prefijo 'v'
          # re-etiquetar el mismo build del SHA a :X.Y.Z y pushear
          docker pull "$IMAGE:${GITHUB_SHA}"
          docker tag  "$IMAGE:${GITHUB_SHA}" "$IMAGE:${SEMVER}"
          docker push "$IMAGE:${SEMVER}"
