name: Build & Push (Docker Hub)
on:
  push:
    paths:
      - "apps/**"
      - ".github/workflows/build-images.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { service: [coordinator, worker-pool, worker-cpu] }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push
        run: |
          IMAGE="docker.io/${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}"
          docker build -t "$IMAGE:${{ github.sha }}" -t "$IMAGE:latest" "apps/${{ matrix.service }}"
          docker push "$IMAGE:${{ github.sha }}"
          docker push "$IMAGE:latest"
