name: Build & Push (Docker Hub)
on:
  push:
    paths:
      - "apps/**"
      - ".github/workflows/build-images.yml"
  workflow_dispatch: {}

permissions:
  contents: write   # <-- para poder commitear el cambio del manifest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set vars
        run: |
          echo "IMAGE_REPO=docker.io/${{ secrets.DOCKER_USERNAME }}/coordinator" >> $GITHUB_ENV
          echo "TAG=${{ github.sha }}" >> $GITHUB_ENV
          # Si querés otro formato de tag:
          # echo "TAG=v${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: apps/coordinator
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.TAG }}
            ${{ env.IMAGE_REPO }}:latest

      # Instalar yq para editar YAML
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      # ACTUALIZA tu manifest para usar el tag inmutable recién publicado
      # Ajustá la ruta si tu archivo no está en la raíz
      - name: Bump image in coordinador.yaml
        env:
          MANIFEST: Infra/k8s/manifests/coordinador.yaml   # <- tu ruta
          CONTAINER_NAME: coordinador                      # <- coincide con el YAML que pasaste
          IMAGE_REPO: docker.io/***/coordinator            # <- tu repo
        run: |
          yq -i '(.spec.template.spec.containers[] | select(.name == env(CONTAINER_NAME)).image) = (env(IMAGE_REPO) + ":" + env(TAG))' "$MANIFEST"
          echo "Preview post-change:"
          grep -nE "image:|name:" "$MANIFEST" || true


      - name: Commit & Push manifest change
        run: |
          git config user.name  "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git add coordinador.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: bump coordinator -> ${{ env.IMAGE_REPO }}:${{ env.TAG }}"
          git push


