name: Build & Push (Docker Hub)
on:
  push:
    paths:
      - "apps/**"
      - ".github/workflows/build-images.yml"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { service: [coordinator, worker-pool] }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push
        run: |
            set -euo pipefail
            IMAGE="docker.io/${{ secrets.DOCKER_USERNAME }}/coordinator"
            docker build -t "$IMAGE:${{ github.sha }}" -t "$IMAGE:latest" apps/coordinator
            docker push "$IMAGE:${{ github.sha }}"
            docker push "$IMAGE:latest"

