name: Build & Push (Docker Hub)

on:
  push:
    paths:
      - "apps/**"
      - ".github/workflows/build-images.yml"
    tags:
      - "v*"              # también corre cuando empujás tags vX.Y.Z
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Login a Docker Hub
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build y push con dos tags: SHA y latest
      - name: Build & Push (SHA + latest)
        run: |
          set -euo pipefail
          IMAGE="docker.io/${{ secrets.DOCKER_USERNAME }}/coordinator"
          docker build -t "$IMAGE:${{ github.sha }}" -t "$IMAGE:latest" apps/coordinator
          docker push "$IMAGE:${{ github.sha }}"
          docker push "$IMAGE:latest"

      # Si el push fue por un tag vX.Y.Z, publica también :X.Y.Z
      - name: Tag & Push SemVer (si aplica)
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        run: |
          set -euo pipefail
          IMAGE="docker.io/${{ secrets.DOCKER_USERNAME }}/coordinator"
          SEMVER="${GITHUB_REF_NAME#v}"   # quita el prefijo 'v'
          docker pull "$IMAGE:${GITHUB_SHA}"        # el build anterior por SHA
          docker tag  "$IMAGE:${GITHUB_SHA}" "$IMAGE:${SEMVER}"
          docker push "$IMAGE:${SEMVER}"
