name: Deploy to GKE
on:
  workflow_run:
    workflows: ["Build & Push (Docker Hub)"]
    types: [completed]
  workflow_dispatch: {}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          # usa el mismo commit que disparó el workflow_run o el SHA actual si es manual
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_LOCATION }}

      - name: Debug tree (opcional)
        run: |
          pwd
          ls -R Infra/k8s
          git ls-files Infra/k8s/manifests

      - name: Apply manifests
        run: |
          kubectl apply -R -f Infra/k8s/manifests/
          kubectl -n integrador rollout status deploy/coordinator --timeout=180s || true
          kubectl -n integrador rollout status deploy/worker-pool --timeout=180s || true
          kubectl -n integrador rollout status deploy/worker-cpu --timeout=180s || true

      - name: Rollout restart (pull latest)  # si usás :latest
        run: |
          kubectl -n integrador rollout restart deployment/coordinator || true
          kubectl -n integrador rollout restart deployment/worker-pool || true
          kubectl -n integrador rollout restart deployment/worker-cpu || true
