name: Deploy to GKE
on:
  workflow_run:
    workflows: ["Build & Push (Docker Hub)"]
    types: [completed]
  workflow_dispatch: {}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - uses: google-github-actions/get-gke-credentials@v2
        with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
                cluster_name: ${{ secrets.GKE_CLUSTER }}
                location: ${{ secrets.GKE_LOCATION }} 

      - name: Render coordinator (IMAGE_TAG = commit SHA)
        run: |
            sudo apt-get update && sudo apt-get install -y gettext-base
            export GITHUB_SHA=${{ github.sha }}
            envsubst < Infra/k8s/manifests/coordinador.yaml > /tmp/coordinador.yaml

      - name: Apply manifests
        run: |
          kubectl apply -f Infra/k8s/manifests/rabbitmq.yaml
          kubectl apply -f Infra/k8s/manifests/redis.yaml
          kubectl apply -f Infra/k8s/manifests/coordinador.yaml
          kubectl apply -f Infra/k8s/manifests/worker-pool.yaml
          kubectl apply -f /tmp/coordinador.yaml

      - name: Wait for rollouts
        run: |
          kubectl -n integrador rollout status deploy/rabbitmq --timeout=180s || true
          kubectl -n integrador rollout status deploy/redis-integrador --timeout=180s || true
          kubectl -n integrador rollout status deploy/coordinator --timeout=180s || true
          kubectl -n integrador rollout status deploy/worker-pool --timeout=180s || true
