name: Terraform (GKE infra)
on:
  pull_request: { paths: ["infra/terraform/**"] }
  push:
    branches: [ main ]
    paths: ["infra/terraform/**"]

jobs:
  tf:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    defaults: { run: { working-directory: infra/terraform } }
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform validate
      - if: github.event_name == 'pull_request'
        run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="region=us-east1" -var="zone=us-east1-c"
      - if: github.event_name == 'push'
        run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="region=us-east1" -var="zone=us-east1-c"
